name = "NBodyProblem"
uuid = "7ec7aa2d-e1e8-49fd-8b2f-0bf01532ae7c"
authors = ["Naoya Ozaki"]
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ParameterizedFunctions = "65888b18-ceab-5e60-b2b9-181511a3b968"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SPICE = "5bab7191-041a-5c2e-a744-024b9c3a5062"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
